{% raw %}
name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          pip install cookiecutter tox

      - name: Lint & Unit Test
        run: |
          tox -q

      - name: Build image
        run: |
          docker build -t ${{ github.repository }}:${{ github.sha }} .

      - name: Push image (skip for forks)
        if: github.ref == 'refs/heads/main'
        run: echo "push to registry here"
{% endraw %}
