apiVersion: v1
kind: Service
metadata:
  name: {{ include "{{ cookiecutter.project_slug }}.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: {{ include "{{ cookiecutter.project_slug }}.name" . }}
