apiVersion: skaffold/v4beta6
kind: Config

metadata:
  name: {{ cookiecutter.project_slug }}

build:
  artifacts:
    - image: {{ cookiecutter.project_slug }}
      context: .
      docker:
        dockerfile: Dockerfile        # auto-switches by language

deploy:
  helm:
    releases:
      - name: {{ cookiecutter.project_slug }}
        chartPath: chart
        valuesFiles: [chart/values.yaml]

profiles:
  - name: dev
    build:
      local:
        push: false          # keep images inside kind/Colima
    deploy:
      helm:
        hooks:
          after:
            - host:
                command: ["kubectl", "rollout", "status", "deployment/{{ cookiecutter.project_slug }}"]
